### PR TITLE
Kisrobot és játékos parancs controller

### PR DESCRIPTION
**Pull request by nyari**
Felmerült egy-két kérdés meg kéne vitatni. Még ne merge-eljetek

### CODE REVIEW

**Comment by nyari** [comment]
Summon @Gustorn. In theroy I'm completed it now, even added your Logger to my new command based controller.
Please review it.

**Comment by Gustorn** [comment]
You should remove the exceptions (and all the command validation) from `procesProtoCommand`. By the time we constructed the `ProtoCommand`, it is guaranteed to contain a valid command and valid arguments for said command. If that's not the case, parsing will fail in the `CommandParser`. This is doing double validation, and we'd have to wrap it in an unnecessary `try...catch` block.

**Comment by nyari** [comment]
Okay. Wait a sec...

**Comment by nyari** [comment]
I'd corrected it. @Gustorn

**Comment by Gustorn** [comment]
You haven't pushed the commit.

**Comment by nyari** [comment]
Oh... :P

**Comment by Gustorn** [comment]
Yeah, seems fine now. I love the no switch on strings policy in Java 6. It was a really well though out design decision...

**Pull request merged**
