### PR TITLE
Ported build scripts to Python

### LINKED ISSUE #45: Javadoc generation
As of #40 we now support JavaDoc to LaTeX generation. This has two (potential) issues:

1. It inserts the JavaDoc generated content at the beginning of the documentation. I feel like adding it to the end would be a better default.
2. It's in English, while the rest of the document is in Hungarian. After a bit of research I believe JavaDoc translations are commonly done with a custom doclet, but unfortunately we already use one for the LaTeX generation. Can we modify it somehow, or is this not an issue?

### LINKED ISSUE #153: Gradle enviromental variables
Set Gradle to use a directory that's guaranteed to be R/W (namely the project directory) on all platforms. Unfortunately `$HOME` is read-only on the lab PCs. 

I'll do this soon, but I'll post the issue as a reminder.

### PR DESCRIPTION
**Pull request by Gustorn**
Rewrote the build scripts, so we actually have a cross-platform way of building the docs (especially the file list generation, which will have to be rebuilt in later stages of developement). The scripts are written so they work on both Python 2 and 3. It's also easy to add custom build commands:

**Command components** can be added in `lib/scripts/commands/<command>.py`: these are the building blocks for more complicated commands.
**Command arguments** are defined in `build_docs.json`. The name of the json value will be the name of the command you have to pass to `./build_docs.py`, and the array contains the name of the command components that will be run (in order).

**Predefined commands:**
- `all`: builds JavaDoc, converts `svg` to `pdf`, generates file list and runs pdflatex
- `svg`: converts `svg` to `pdf`
- `file-list`: generates file list in LaTeX format
- `javadoc`: generates JavaDoc 

**Other changes:**
- the new command name is `./build_docs.py <command name>`. As mentioned earlier, the commands are defined in `build.json`
- the SVG build scripts now detects the last modification date. If the svg file is newer than the generated pdf then it will be rebuilt. If it's not it will be skipped.
- Python has better regexes (or at the least it's easier to parse as a human) than shell scripts, so the pdflatex output normaliztion should be improved.
- Fixed JavaDoc generation, now submodules are automatically added to the `-submodules` parameter. This pretty much guarantees that documentation will be generated for all classes.
- Executing `./build_docs.py` builds all the documentation.

**Downsides:**
- this needs a Python installation (obviously): this should be preinstalled on most Linux distros and OS X, but it's not on Windows. 

All in all, the downside is minimal (and I can't think of an easier cross platform solution). Even our current method needed the GNU userland on Windows to work (and it didn't even work on OS X). With the Python 2/3 compatibility I don't really think there's a better alternative.

Also closes #153, but I'll submit this anyway if this is not going to get merged.

EDIT: this also closes #45

/cc @gregory094 @istvanszoke

### CODE REVIEW

**Comment by Gustorn** [comment]
GitHub's having some issues, that's why Travis is failing, just rerun the Travis build before you merge.

**Comment by nyari** [comment]
Én megnéztem. :) Ha @gregory094 és @istvanszoke is kipróbálja akkor szerintem mehet...

**Comment by gregory094** [comment]
@istvanszoke  ha kipróbálta, akkor mergelném be, mert nálam is megy.

**Comment by istvanszoke** [comment]
Tegnap megvolt. Mehet a merge

2015-03-29 12:00 GMT+02:00 Nagy Gergő <notifications@github.com>:

**Comment by gregory094** [comment]
Okés. Fogom mindjárt.

**Comment by gregory094** [comment]
+1

**Pull request merged**
