### PR TITLE
Issue#21

### PR DESCRIPTION
**Pull request by Gustorn**
Added initial support for Travis and Gradle (the Java build system). We still need to test if JUnit tests build and run correctly on Travis. 

Even though we are most likely targetting Java 6, Travis only supports the Oracle JDK >= 7.0, so we are building against OpenJDK 7 and OracleJDK 7.

### CODE REVIEW

**Comment by Gustorn** [comment]
Just as an addition: we shouldn't close the Issue as of yet, I'll work some more on the JUnit side of things.

**Comment by gregory094** [comment]
Travis should handle the JUnit framework correctly. We'll see...
In the docs of Travis I've read about the support of JDK 6.
http://docs.travis-ci.com/user/languages/groovy/

**Comment by Gustorn** [comment]
According to [the official docs](http://docs.travis-ci.com/user/languages/java/) only OpenJDK and OracleJDK 6 is supported. It doesn't make too much sense building against OpenJDK 6 when version 7 should be backwards compatibile anyway. 

While Travis should indeed handle JUnit fine, I'm more concerned about the Gradle configuration.

**Comment by gregory094** [comment]
As far as I know the policy of the course states Java 6 is the only version tolerated.  I do not want to run into superset-subset problems.

**Pull request merged**
